# **Numpy** 

In [2]:
import numpy as np

In [41]:
a1=np.array([1,52,4,3])
print("itemsize:",a1.itemsize)  #size of int
print("size:",a1.size)          # numbers of element in array
print("dtype:",a1.dtype)

itemsize: 4
size: 4
dtype: int32


In [50]:
zero_array=np.zeros((3,2),dtype="int32")
print("zeroes:\n",zero_array)
ones_array=np.ones((3,2),dtype="int32")
print("ones:\n",ones_array)

zeroes:
 [[0 0]
 [0 0]
 [0 0]]
ones:
 [[1 1]
 [1 1]
 [1 1]]


In [56]:
one2ten=np.arange(1,11) # it does not include 11
one2tenwithsteps=np.arange(1,11,2)
linerspace=np.linspace(0,20,5,dtype="int32")

print(one2ten)
print(one2tenwithsteps)
print(linerspace)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ 0  5 10 15 20]


In [60]:
arr1=np.array([[1,5],[64,4],[1,5]])
print("Reshaped:\n",arr1.reshape(2,3))
print("Falt/Ravel:\n",np.ravel(arr1))  # Ravel change dimension into 1

Reshaped:
 [[ 1  5 64]
 [ 4  1  5]]
Falt/Ravel:
 [ 1  5 64  4  1  5]
