In [1]:
import numpy as np

## Creation

<strong> 1.np.array

In [10]:
arr1=np.array((range(1,11))) # Tuple into numpy array
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr2=np.array([range(1,11)]) # list into numpy array 
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

<strong>2.np.zeroes

In [14]:
zeroes_np= np.zeros((4,5)) 
zeroes_np

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<strong>3.np.ones

In [15]:
ones_np=np.ones((4,5))
ones_np

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

<strong>4.Identity np

In [19]:
iden_np= np.identity(5) #identity is a square matrix having 1 in its diagonal values.
iden_np

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<strong>5. np.arange

In [22]:
start=1
end= 10
step=4
arr3= np.arange(start,end,step)
arr3

array([1, 5, 9])

<strong>6.Linspace array

In [25]:
lin_np=np.linspace(start,end,4) # 4 numbers b/w start and end having equal space.
lin_np

array([ 1.,  4.,  7., 10.])

<strong>7.copy

In [28]:
c=lin_np
c

array([ 1.,  4.,  7., 10.])

In [27]:
copy_np= np.copy(lin_np)
copy_np

array([ 1.,  4.,  7., 10.])

<strong>8.np.random

In [30]:
randfloat_np= np.random.uniform(1,50,10)
randint_np= np.random.randint(1,50,10)
print("Random float array:",randfloat_np)
print("Random int array:",randint_np)

Random float array: [34.51411028 47.50999422 41.0950701  41.50891915 11.08227999 18.04392153
 38.5054819  14.53080873 42.56484837 22.51338216]
Random int array: [20 32 18 28  4 41 48 40 47 19]


## Attributes

<strong>1.Shape

In [51]:
arr3=np.array([[1,2,6],[1,3,4]])
arr3.shape

(2, 3)

<strong>2.ndim

In [40]:
arr3.ndim

2

<strong>3.size

In [41]:
arr3.size

6

<strong>4. itemsize

In [42]:
arr3.itemsize

4

<strong>5.dtype

In [44]:
arr3.dtype

dtype('int32')

<strong>6. astype

In [50]:
arr3_float=arr3.astype("float")
print(arr3_float.dtype)
arr3_float

float64


array([[1., 2., 6.],
       [1., 3., 4.]])

## Slicing And Accessing

In [53]:
arr4= np.arange(1,21).reshape(5,4)
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [54]:
arr4[0]

array([1, 2, 3, 4])

<strong> Continous Slicing

In [57]:
arr4[:,3]      # 4th column of every row

array([ 4,  8, 12, 16, 20])

In [60]:
arr4[:,1:3]    # 1 to 3(excluding 3) of every row

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [63]:
arr4[1:3,:3]   # 0 to 3 column of 1 to 3 row

array([[ 5,  6,  7],
       [ 9, 10, 11]])

<strong> Discontinous Slicing

In [66]:
arr4[:,[1,3]]     # 1 and 3 column of every row

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [68]:
arr4[[0,2,4]][:,[0,2]]   # 0 and 2 column of 0,2 and 4 row

array([[ 1,  3],
       [ 9, 11],
       [17, 19]])

<strong> Conditional Accessing

In [185]:
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [188]:
arr4>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [187]:
arr4[arr4>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [190]:
arr4[(arr4>5) & (arr4<15)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

## Basic Mathematical Operations

<strong> Arithmetics

In [84]:
arr6= np.arange(16,31).reshape(3,5)
arr6

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [74]:
arr5=np.arange(1,16).reshape(3,5)
arr5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [75]:
arr5*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [85]:
arr5*arr6

array([[ 16,  34,  54,  76, 100],
       [126, 154, 184, 216, 250],
       [286, 324, 364, 406, 450]])

In [76]:
arr5+2

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17]])

In [86]:
arr5+arr6

array([[17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45]])

In [87]:
arr6-arr5 

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [81]:
arr5-10

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5]])

In [88]:
arr6/arr5

array([[16.        ,  8.5       ,  6.        ,  4.75      ,  4.        ],
       [ 3.5       ,  3.14285714,  2.875     ,  2.66666667,  2.5       ],
       [ 2.36363636,  2.25      ,  2.15384615,  2.07142857,  2.        ]])

In [77]:
arr5/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [89]:
arr6%arr5

array([[0, 1, 0, 3, 0],
       [3, 1, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [79]:
arr5%5

array([[1, 2, 3, 4, 0],
       [1, 2, 3, 4, 0],
       [1, 2, 3, 4, 0]], dtype=int32)

In [90]:
arr6**arr5

array([[         16,         289,        5832,      130321,     3200000],
       [   85766121, -1800609408,  1001573953,   402653184,  1977800241],
       [-1420187648, -1953380655, -1677721600,  1779365433, -2080931840]])

In [80]:
arr5**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

<strong> Dot Product

In [95]:
arr6=arr6.reshape(5,3)    # arr5(m,n) and arr6(p,q) n should be equal to p.
print(arr5.shape)
arr5.dot(arr6)

(3, 5)


array([[ 360,  375,  390],
       [ 910,  950,  990],
       [1460, 1525, 1590]])

<strong> Statical Operations

In [102]:
arr7=np.random.randint(1,50,15).reshape(3,5)
arr7

array([[25,  7, 39,  7,  8],
       [ 7,  5, 40,  8,  8],
       [49, 47, 31, 21, 34]])

In [107]:
arr7.min()  # it gives the minimum value from the numpy array

5

In [103]:
arr7.min(axis=0)   #it gives the min value from each column.

array([ 7,  5, 31,  7,  8])

In [104]:
arr7.min(axis=1) # it gives the min values from each row 

array([ 7,  5, 21])

In [105]:
arr7.max() #optional axis=0,1

49

In [108]:
arr7.mean() #optional axis=0,1

22.4

In [119]:
arr7.sum()

336

In [109]:
np.median(arr7)

21.0

In [110]:
np.exp(arr7)  # exp(2)---> e=2.71828**2

array([[7.20048993e+10, 1.09663316e+03, 8.65934004e+16, 1.09663316e+03,
        2.98095799e+03],
       [1.09663316e+03, 1.48413159e+02, 2.35385267e+17, 2.98095799e+03,
        2.98095799e+03],
       [1.90734657e+21, 2.58131289e+20, 2.90488497e+13, 1.31881573e+09,
        5.83461743e+14]])

In [113]:
np.sqrt(arr7)

array([[5.        , 2.64575131, 6.244998  , 2.64575131, 2.82842712],
       [2.64575131, 2.23606798, 6.32455532, 2.82842712, 2.82842712],
       [7.        , 6.8556546 , 5.56776436, 4.58257569, 5.83095189]])

In [115]:
np.std(arr7)

15.814761037292554

In [116]:
np.argmax(arr7) # return index of max element assuming it a 1d array

10

In [117]:
np.argmin(arr7) ## return index of min element assuming it a 1d array

6

## Reshaping

In [120]:
arr8=arr7
arr8

array([[25,  7, 39,  7,  8],
       [ 7,  5, 40,  8,  8],
       [49, 47, 31, 21, 34]])

In [121]:
arr8.ravel()  # converts n-dim array in 1d array.

array([25,  7, 39,  7,  8,  7,  5, 40,  8,  8, 49, 47, 31, 21, 34])

In [124]:
print(arr8.size)
print(arr8.shape)

15
(3, 5)


In [128]:
arr8.reshape(5,3) # returns a new array of new shape 

array([[25,  7, 39],
       [ 7,  8,  7],
       [ 5, 40,  8],
       [ 8, 49, 47],
       [31, 21, 34]])

In [131]:
arr8.reshape(3,1,5) # reshaping into 3d array

array([[[25,  7, 39,  7,  8]],

       [[ 7,  5, 40,  8,  8]],

       [[49, 47, 31, 21, 34]]])

<strong>Shape should give size as its multiplication result.

In [132]:
arr8

array([[25,  7, 39,  7,  8],
       [ 7,  5, 40,  8,  8],
       [49, 47, 31, 21, 34]])

In [138]:
arr8.transpose()  # shape (x,y)----> (y,x)

array([[25,  7, 49],
       [ 7,  5, 47],
       [39, 40, 31],
       [ 7,  8, 21],
       [ 8,  8, 34]])

In [165]:
hp1= np.arange(1,11).reshape(5,2)
hp2= np.arange(11,21).reshape(5,2)

In [166]:
hp1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [167]:
hp2

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [171]:
h_stacked=np.hstack((hp1,hp2))
h_stacked

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [170]:
v_stacked=np.vstack((hp1,hp2))
v_stacked

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [184]:
np.hsplit(h_stacked,4)

[array([[1],
        [3],
        [5],
        [7],
        [9]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]]),
 array([[11],
        [13],
        [15],
        [17],
        [19]]),
 array([[12],
        [14],
        [16],
        [18],
        [20]])]

In [183]:
np.vsplit(v_stacked,5)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]),
 array([[13, 14],
        [15, 16]]),
 array([[17, 18],
        [19, 20]])]

## Extra 

<strong>1.nditer

In [192]:
arr9= np.random.randint(0,20,10)
arr9

array([10, 12,  1,  0,  7, 19, 18, 17,  2, 19])

In [199]:
for i in np.nditer(arr9):
    print(i,end="  ")

10  12  1  0  7  19  18  17  2  19  

In [197]:
arr10=arr9.reshape(5,2)
arr10

array([[10, 12],
       [ 1,  0],
       [ 7, 19],
       [18, 17],
       [ 2, 19]])

In [198]:
for i in np.nditer(arr10):
    print(i,end="  ")

10  12  1  0  7  19  18  17  2  19  

<strong>2. assigning

Here we will make an array with range(1,20) and we will change the odd numbers in the array by adding 1 into it.

In [201]:
num_arr= np.arange(1,20)
num_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [208]:
num_arr[num_arr%2 !=0]+=1
num_arr

array([ 2,  2,  4,  4,  6,  6,  8,  8, 10, 10, 12, 12, 14, 14, 16, 16, 18,
       18, 20])

Now what if i do not want to alter the original array so we can just apply np.where which will gives us a new array.

##### Where

In [214]:
even_arr= np.where(num_arr%2 !=0,num_arr+1,num_arr)
even_arr

array([ 2,  2,  4,  4,  6,  6,  8,  8, 10, 10, 12, 12, 14, 14, 16, 16, 18,
       18, 20])

<strong>3. Sort

In [236]:
np.random.seed(1)
arr10= np.random.randint(1,20,10)
np.sort(arr10)

array([ 1,  6,  6,  9, 10, 12, 12, 13, 16, 17])

In [240]:
arr10

array([ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17])

In [242]:
arr11=arr10.reshape(2,5)
arr11

array([[ 6, 12, 13,  9, 10],
       [12,  6, 16,  1, 17]])

In [245]:
np.sort(arr11,axis=0)   # Sorted on columns

array([[ 6,  6, 13,  1, 10],
       [12, 12, 16,  9, 17]])

In [247]:
np.sort(arr11,axis=1)  # Sorted on rows

array([[ 6,  9, 10, 12, 13],
       [ 1,  6, 12, 16, 17]])

<strong>4.Percentile

In [249]:
np.random.seed(1)
per_arr= np.random.randint(1,20,10)
per_arr

array([ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17])

In [251]:
np.sort(per_arr)

array([ 1,  6,  6,  9, 10, 12, 12, 13, 16, 17])

In [256]:
np.percentile(per_arr,80)

13.600000000000001